"use strict";

function str_obj(str) {
  str = str.split("; ");
  var result = {};

  for (var i = 0; i < str.length; i++) {
    var cur = str[i].split("=");
    result[cur[0]] = cur[1];
  }

  return result;
}

var lang = str_obj(document.cookie).lang;
var about_es_title = "Quienes somos";
var about_es =
  "<p>En Ivanmet S.A. contamos con m\xE1s de 30 a\xF1os de experiencia en proveer servicios de log\xEDstica integral, desde el retiro de los materiales en origen, hasta su entrega en destino final.</p>\n<p>Con nuestra atenci\xF3n personalizada, Ud. estar\xE1 informado en cada momento del status de sus materiales.</p>\n<p>Para nosotros no hay cargas peque\xF1as ni grandes. Todas nuestras operaciones merecen la dedicaci\xF3n y los est\xE1ndares de calidad que su empresa requiere.</p>\n<b>Compromiso de calidad Ivanmet.</b>";
var about_en_title = "About Us";
var about_en =
  "<p>Ivanmet S.A. is a company with over 30 years of experience in providing logistic services,\nstarting with the pickup of your goods at origin, until the delivery at their final destination.</p>\n<p>With our personalized customer attention, you'll be informed at each step about the status of your goods.\n</p>\n<p> For us there is no difference in sizes handling cargo. All our operations deserve our dedication and the quality standards your company requires.</p>\n<b>Quality Commitment Ivanmet.</b>";
var clientes_es_title = "Clientes";
var clientes_es =
  "A continuaci\xF3n detallamos los principales clientes a los que tenemos el gusto de proveer con nuestros servicios.<br>\nSi a\xFAn no es cliente nuestro, esperamos pronto contar con Ud.";
var clientes_en_title = "Customers";
var clientes_en =
  "Below we detail the main customers we are pleased to provide with our services.<br>If you are not yet our client, we hope to have you soon.";
var contact_en_title = "Contact";
var contact_en =
  "<p>For questions you may have or more information about us or our services, do not hesitate to contact us.</p>";
var contact_es_title = "Contacto";
var contact_es =
  "<p>Por consultas o mayor informaci\xF3n sobre nosotros o nuestros servicios no dude en contactarnos.</p>";
var agenteCarga_en_title = "Freight Agent";
var agenteCarga_es_title = "Agentes de carga";
var agenteCarga_en =
  "<p>For more than 20 years, we are integrating the global network of international freight forwarders World Net Associates (WNA).\n</p>\n<p>\nThat is the reason why we can offer competitive rates in each mode of transportation to you with availability, regularity and frequency bases for your materials.</p>\n<ul>\n<li>Pickup, receiving and inspection.\n</li>\n<li>Packaging\n</li>\n<li>Air Freight - consolidated and complete.\n</li>\n<li> Maritime Freight - LCL and FCL - Special Containers - Chartering.\n</li>\n<li> Trucking Freight - Consolidated and Full service - Inland Freight throughout Argentina.\n</li>\n<li>Managment of hazardous cargoes.\n</li>\n</ul>";
var agenteCarga_es =
  "<p>Desde hace m\xE1s de 20 a\xF1os, nos hemos integrado a la red global de agentes de carga internacional World Net Associates (WNA).</p>\n<p>As\xED es que podemos ofrecer tarifas competitivas en cada modalidad de transporte. Disponibilidad, regularidad y frecuencia.</p>\n<ul>\n<li> Retiro, recepci\xF3n e inspecci\xF3n.\n</li>\n<li> Embalajes\n</li>\n<li> Cargas a\xE9reas - consolidadas y completas.\n</li>\n<li> Mar\xEDtimas - LCL y FCL - Contenedores Especiales - Chartering.\n</li>\n<li> Terrestres - Consolidados y Completos - Servicio de flete a toda la Argentina.\n</li>\n<li> Gesti\xF3n de cargas peligrosas.\n</li>\n</ul>";
var servicioCarga_en_title = "Project Cargo";
var servicioCarga_es_title = "Carga de Proyecto";
var servicioCarga_en =
  "<p>We provide a complete logistic service from the departure in origin to the delivery at the final destination, covering each of the intermediate stages including the corresponding customs destination.</p><p>We have the necessary experience to obtain the best results in the planned times.</p>";
var servicioCarga_es =
  "<p>Proveemos un servicio log\xEDstico completo desde el retiro en origen hasta la entrega en destino final, cubriendo\ncada una de las etapas intermedias incluyendo la destinaci\xF3n aduanera correspondiente.</p><p>Contamos con la experiencia\nnecesaria para obtener el mejor de los resultados en los tiempos planificados.\n</p>";
var serviciosAduaneros_en_title = "Customs Services";
var serviciosAduaneros_es_title = "Servicios Aduaneros";
var serviciosAduaneros_en =
  "<h3>Advicing</h3>\n<p>At Ivanmet we only think of you, that is the reason why we are always at your service to support and advise you on the best customs criteria applicable to your needs.</p>\n<h3>Harmonized Tariff Schedule (HTS)</h3>\n<p>One of our strengths is a correct and effective harmonized tariff classification, with an important background capitalization through all the years of experience in the matter. This will allow you to tax and manifest to customs what you are actually importing or exporting.</p>\n<h3>Customs Management throughout the Country</h3>\n<p>We have a network of agents throughout the country, which we supervise and gives us complete confidence that your operations are in the best hands.</p>\n<h3>Special regimes</h3>\n<p>We have the knowledge and we are in line with the latest Customs regulations.</p>\n<h3>Off-Shore Management</h3>\n<p>From our origins, we have participated in this type of management, with knowledge and application of the specific regulations. Providing an integral logistics service that at the conclusion of each operation, we have demonstrated the level of efficiency achieved.</p>";
var serviciosAduaneros_es =
  "<h3>Asesoramiento</h3>\n<p>En Ivanmet solo pensamos en Ud. <br>Por esto es que siempre estamos a su disposici\xF3n para apoyarlos y asesorarlos\nen el mejor criterio aduanero aplicable a su necesidad.</p>\n<h3>Clasificaci\xF3n Arancelaria</h3>\n<p>Una de nuestras fortalezas es una correcta y efectiva clasificaci\xF3n arancelaria, contando con un importante\nbackground a trav\xE9s de todos los a\xF1os de experiencia en la materia.<br>Esto le permitir\xE1 tributar y manifestar ante\nla aduana lo que Ud. efectivamente esta importando o exportando.</p>\n<h3>Gesti\xF3n Aduanera en todo el Pa\xEDs</h3>\n<p>Contamos con una red de agentes en todo el pa\xEDs, la cual supervisamos y nos brinda una total tranquilidad de que\nsus operaciones est\xE1n en las mejores manos.</p>\n<h3>Reg\xEDmenes Especiales</h3>\n<p>Tenemos el conocimiento y estamos en l\xEDnea con las ultimas normativas.</p>\n<h3>Gesti\xF3n Off-Shore</h3>\n<p>Desde nuestros or\xEDgenes, hemos participado en este tipo de gesti\xF3n, con conocimiento y aplicaci\xF3n de la\nnormativa especifica. Suministrando un servicio log\xEDstico integral que al concluir cada operaci\xF3n, hemos demostrado el\nnivel de eficiencia alcanzado.</p>";
var serviciosOficina_es_title = "Oficina Externa de Compras Internacionales";
var serviciosOficina_en_title = "External Office of International Purchases";
var serviciosOficina_es =
  "<p>Contamos con una selecta red de proveedores a trave\u0301s de los que estamos en condiciones de suplir las mu\u0301ltiples\ndemandas del mercado. Le podemos ofrecer desde la b\xFAsqueda del producto hasta la puesta en destino final.</p><p>Si Ud.\naun no es importador, tambi\xE9n podemos acordar una gesti\xF3n de compra por su cuenta generando finalmente una venta\nen plaza del producto.</p>";
var serviciosOficina_en =
  "<p>We manage a select network of suppliers through which we are able to meet the multiple demands of the market. We can offer you from the search of the product to the delivery at final destination.</p><p>If you are not yet an importer, we can also provide on a purchase management agree on your own and finally generating a sale in place of a local product.</p>";
var serviciosSeguros_es_title = "Seguros de Transporte";
var serviciosSeguros_en_title = "Transportation Insurance";
var serviciosSeguros_es =
  "<p>Ponemos a su disposici\xF3n la contrataci\xF3n del seguro para la cobertura de riesgo de sus productos transportados. Trabajamos con aseguradoras de primer nivel que garantizan la responsabilidad en el riesgo.</p>\n</p>";
var serviciosSeguros_en =
  "<p>We offer you the insurance contract for the risk coverage of your transported products. We work with first level insurers that guarantee the responsibility in the risk.</p>";
var expertise_en = "<ul><li>TOTAL LOGISTICS SERVICES (FREIGHT FORWARDER/CUSTOM CLEARANCE) \nGAS PLANT IN SIERRA CHATA , NEUQUEN \u2013 PETROLERA SANTA FE/\nPETROBRAS.</li><hr/>\n<li>TOTAL LOGISTICS SERVICES ( FREIGHT FORWARDER/CUSTOM CLEARANCE) FOR PROJECT \u201CEL TRAPIAL\u201D RESERVOIR \u2013 PETROLERA SAN JORGE/ CHEVRON ARGENTINA</li><hr/>\n<li>TOTAL LOGISTICS SERVICES ( FREIGHT FORWARDER/CUSTOM CLEARANCE) CARGO AIRCRAFT ANTONOV - SNUBBING EQUIPMENT \u2013 \u201CEL TRAPIAL\u201D RESERVOIR \u2013 PETROLERA SAN JORGE/ CHEVRON ARGENTINA</li><hr/>\n<li>LOGISTICS FOR THE UNLOADING OF CARGO AIRCRAFT 'ANTONOV', CUSTOM CLEARANCE, FOR PETROLERA SANTA FE, 'WELLHEAD EQUIPMENT' FOR CERRO ARENA AND COMPRESSOR 4000 HP FOR SIERRA CHATA.</li><hr/>\n<li>CUSTOMS SERVICES FOR OFFSHORE OPERATIONS IN CARINA AND ARIES\u2019 AREAS, WEATHERFORD SERVICES FOR TOTAL AUSTRAL\u2019S AREAS.</li><hr/>\n<li>TOTAL LOGISTICS SERVICES ( FREIGHT FORWARDER/CUSTOM CLEARANCE) FOR PROJECT \u201CEL CORCOVO\u201D RESERVOIR- PETROANDINA/PLUSPETROL</li><hr/>\n<li>TOTAL LOGISTICS SERVICES (FREIGHT FORWARDER / CUSTOM CLEARANCE) FOR PROJECT \u201CBLOQUE FELL\u201DCHILE RESERVOIR-GEOPARK  CHILE.</li><hr/>\n<li>TOTAL LOGISTICS SERVICES ( FREIGHT FORWARDER/CUSTOM CLEARANCE) FOR PROJECT \u201CRUSSFIN\u201D AND \u201CLENGA\u201D APACHE\u2019S AREAS, CHILE</li><hr/>\n<li>TOTAL LOGISTICS SERVICES (FREIGHT FORWARDER / CUSTOMS CLEARANCE) FOR IMPORT OF THE CABLELESS LAND SEISMIC ACQUISITION SYSTEM, FIREFLY\xAE, APACHE ENERGIA.</li><hr/>\n<li>TOTAL LOGISTICS SERVICES ( FREIGHT FORWARDER/CUSTOM CLEARANCE) FOR PROJECT \u201CPUNTA DUNGENES\u201D SIPETROL ARGENTINA</li><hr/>\n<li>CUSTOM BROKER FOR GAS \u2018EXPORT TO CHILE FROM NEUQUEN \u2013 PLUSPETROL, EXXON MOBIL, CANADIAN HUNTER AND ATALAYA. </li><hr/>\n<li>TOTAL LOGISTICS SERVICES (FREIGHT FORWARDER / CUSTOM CLEARANCE) FOR THE IMPORT OF THE GAS TREATMENT PLANTS OF C3PLUS /GAS MERIDIONAL.</li><hr/>\n<li>FREIGHT FORWARDING FOR THE TRANSPORTATION OF SPARTAN\u2019S AMINA PLANT FROM BLOQUE FELL RESERVOIR GEOPARK- CHILE TO MEGA BAHIA BLANCA, YPF GAS.</li><hr/>\n<li>FREIGHT FORWARDING FOR THE TRANSPORTATION SPARTAN\u2019S AMINA PLANT FROM BLOQUE FELL RESERVOIR GEOPARK - CHILE BACK TO HOUSTON THROUGH COMODORO RIVADAVIA, GEOPARK CHILE.";
var expertise_es =
  "<ul>\n<li>LOG\xCDSTICA COMPLETA (FREIGHT FORWARDER/DESPACHO DE ADUANA) PARA LA CONSTRUCCI\xD3N, PUESTA EN MARCHA Y FUNCIONAMIENTO DE LA PLANTA DE TRATAMIENTO DE GAS DE PETROLERA SANTA FE (ACTUALMENTE PETROBRAS) EN SIERRA CHATA, NEUQU\xC9N, ARGENTINA.</li>\n<hr/>\n<li>OPERACI\xD3N DE CARGA EN CONDICI\xD3N CHARTER EN AVI\xD3N \u201CANTONOV\u201D AL AEROPUERTO DE NEUQU\xC9N, ARGENTINA, PARA EQUIPAMIENTO \u201CSNUBBING\u201D- PARA YACIMIENTO EL TRAPIAL \u2013 CHEVRON SAN JORGE. FREIGHT FORWARDER/DESPACHO A PLAZA.</li>\n<hr/>\n<li>LOG\xCDSTICA PARA DESCARGA DEL AVI\xD3N \u201CANTONOV\u201D, DESPACHO A PLAZA , PARA PETROLERA SANTA FE, EQUIPAMIENTO PARA CERRO ARENA \u201CWELLHEAD EQUIPMENT\u201D Y COMPRESOR 4000 HP PARA SIERRA CHATA.</li>\n<hr/>\n<li>ASISTENCIA EN OPERACIONES OFF SHORE A EMPRESAS DE SERVICIOS COMO WEATHERFORD DE ARGENTINA PARA EL PROYECTO DEL OPERADOR: TOTAL , EN YACIMIENTOS CARINA Y ARIES EN EL MAR AUSTRAL. DESPACHOS EN ADUANA BS.AS., TR\xC1NSITOS Y GESTI\xD3N DE DESPACHO EN ADUANAS DEL INTERIOR A TRAV\xC9S DE NUESTROS AGENTES.</li>\n<hr/>\n<li>LOG\xCDSTICA COMPLETA (FREIGHT FORWARDER/DESPACHO DE ADUANA/TRANSPORTE INTERNO) PARA EL DESARROLLO DEL YACIMIENTO EL CORCOVO DE PETROANDINA (ACTUALMENTE PLUSPETROL).</li>\n<hr/>\n<li>LOG\xCDSTICA COMPLETA (FREIGHT FORWARDER/DESPACHO DE ADUANA) PARA EL DESARROLLO DEL YACIMIENTO. BLOQUE FELL EN CHILE DE GEOPARK ARG.</li>\n<hr/>\n<li>LOG\xCDSTICA COMPLETA (FREIGHT FORWARDER/DESPACHO DE ADUANA) PARA LAS OPERACIONES DE EXPLORACI\xD3N EN LAS \xC1REAS RUSSFIN Y LENGA EN CHILE DE APACHE ENERGIA.</li>\n<hr/>\n<li>LOG\xCDSTICA COMPLETA (FREIGHT FORWARDER/DESPACHO DE ADUANA) PARA LA IMPORTACI\xD3N DE SISTEMA FIRE FLY PARA TRABAJOS DE S\xCDSMICA DE APACHE ENERGIA.</li>\n<hr/>\n<li>LOG\xCDSTICA COMPLETA (FREIGHT FORWARDER/DESPACHO DE ADUANA) PARA LA CONSTRUCCI\xD3N Y PUESTA EN MARCHA DE LAS INSTALACIONES DE RECEPCI\xD3N Y TRATAMIENTO (BRM) EN PUNTA DUNGENES DE SIPETROL ARGENTINA Y OPERACI\xD3N OFF SHORE.</li>\n<hr/>\n<li>GESTI\xD3N DE DESPACHO DE LAS EXPORTACIONES DE GAS DE TRATAYEN POR GAS ANDES CON APOYO EN NUESTRO AGENTE EN NEUQU\xC9N DESDE COMIENZO DE LA ACTIVIDAD DE PETROLERA SANTA FE (HOY PETR. OBRAS) /EXXONMOBIL/CANADIAN HUNTER/ATALAYA.</li>\n<hr/>\n<li>LOG\xCDSTICA COMPLETA (FREIGHT FORWARDER/DESPACHO DE ADUANA) PARA LAS IMPORTACIONES DE PLANTAS DE TRATAMIENTO DE GAS DE C3PLUS/GAS MERIDIONAL.</li>\n<hr/>\n<li>LOG\xCDSTICA PARA EL TRASLADO DE PLANTA DE AMINAS SPARTAN DESDE BLOQUE FELL GEOPARK CHILE A MEGA BAH\xCDA BLANCA PARA YPF GAS.</li>\n<hr/>\n<li>LOG\xCDSTICA PARA EL TRASLADO DE PLANTA DE AMINAS SPARTAN DESDE BLOQUE FELL GEOPARK CHILE A HOUSTON V\xCDA COMODORO RIVADAVIA PARA GEOPARK.</li>\n</ul>";
